eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
server:
  port: 8060
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: appointments
