eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: quiz
          uri: http://quiz-service:8090
          predicates:
            - Path=/api/quizzes/**
        - id: post
          uri: http://post-service:8070
          predicates:
            - Path=/api/post/**
        - id: workshop
          uri: http://workshop-service:8020
          predicates:
            - Path=/api/workshop/**
        - id: request
          uri: http://request-service:8080
          predicates:
            - Path=/api/request/**
        - id: user
          uri: http://user-service:8050
          predicates:
            - Path=/api/user/**
        - id: appointments
          uri: http://appointments-service:8060
          predicates:
            - Path=/api/appointments/**
        - id: angular
          uri: http://angular-service:4200
          predicates:
            - Path=/**
