eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      mvc:
        routes:
          - id: quiz
            uri: http://localhost:8090
            predicates:
              - Path=/api/quizzes/**
          - id: post
            uri: http://localhost:8070
            predicates:
              - Path=/api/posts/**
          - id: comment
            uri: http://localhost:8070
            predicates:
              - Path=/api/comments/**
          - id: workshop
            uri: http://localhost:8020
            predicates:
              - Path=/api/workshop/**
          - id: request
            uri: http://localhost:8080
            predicates:
              - Path=/api/request/**
          - id: appointments
            uri: http://localhost:8060
            predicates:
              - Path=/api/appointments/**




