eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: quiz
          uri: http://localhost:8090
          predicates:
            - Path=/api/quizzes/**
        - id: post
          uri: http://localhost:8070
          predicates:
            - Path=/api/post/**
        - id: workshop
          uri: http://localhost:8020
          predicates:
            - Path=/api/workshop/**
        - id: request
          uri: http://localhost:8080
          predicates:
            - Path=/api/request/**
        - id: user
          uri: http://localhost:8050
          predicates:
            - Path=/api/user/**
        - id: appointments
          uri: http://localhost:8060
          predicates:
            - Path=/api/appointments/**
        - id: angular
          uri: http://localhost:4200
          predicates:
            - Path=/**