eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8020

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/workshopDB
