apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: doniadrira/angular:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4222


---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 4222       
      targetPort: 4222 
