apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: onshanafi/angular:1.6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80       
      # targetPort: 80 
