apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-app
        image: onshanafi/config-server:1.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server-app
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888




