apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-app
  labels:
    app: discovery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-app
  template:
    metadata:
      labels:
        app: discovery-app
    spec:
      containers:
      - name: discovery-app
        image: onshanafi/discovery:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-app
  type: ClusterIP   
  ports:
    - protocol: TCP
      port: 8761       
      targetPort: 8761 



