apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
      - name: gateway-app
        image: onshanafi/gateway:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8222

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8222       
      targetPort: 8222 



